services:
  - type: web
    name: your-app-name-here
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    buildCommand: "composer install"
    startCommand: "php cron.php"
    autoDeploy: true
    envVars:
      - key: PEXELS_API_KEY
        value: fOuF5nlf1UEsPIEuAeOjNeXpGXZAMCoxJWwNvyMkCyLWB8Oku5LZ4dpQ
      - key: TTS_API_KEY
        value: your_tts_api_key_here
      - key: LANGUAGE
        value: en-bn
